apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-review-app-deplopyment
  labels:
    app: book-review-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-review-app
    spec:
      containers:
      - name: nodeserver
        image: devaaa008/bookreviewapp:latest
        ports:
        - containerport: 5000