apiVersion: v1
kind: Service
metadata:
  name: book-review-app-service
spec:
  selector:
    app: book-review-app
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 31110